drf_and_image_uploads/apps/accounts/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from . import views
from .views import UserDocUpload

# from .views import UserUpload

urlpatterns = [

    # USER URLS
    path('api-token-auth/', UserDocUpload.as_view()),
    path('jobs/', include('jobs.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drf_and_image_uploads/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings

from drf_and_image_uploads.apps.accounts.views import UserDocUpload
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("apply/", TemplateView.as_view(template_name="index.html")),

    # url(r'^api/v1/users/$', 'post'),
    # url(r'^api/v1/users/(?P<pk>[0-9]+)$', 'post_element'),
    path('api-auth/', include('rest_framework.urls')),
    path('jobs/', include('jobs.urls')),
    path("api/auth-token/", obtain_auth_token, name="rest_auth_token"),
    path("api/user-uploads/", UserDocUpload.as_view(), name="rest_user_avatar_upload"),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import RedirectView

from . import views
from .views import UserUpload

urlpatterns = [

    # USER URLS
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.services, name='services'),
    #path('login/', views.user_login, name='login'),

    # ==========================services======================================================================
    # APPLICANT URLS
    # slug is used to generate valid urls
    path('jobs/', views.JobsList.as_view(), name='posted_jobscopy'),
    path('jobs/<slug:slug>/', views.JobsDetail.as_view(), name='posted_jobsdetails'),
    # path('jobs/<int:job_id>/', views.ApplyJobView.as_view(), name='job-details'),
    path('jobs/<int:job_id>/apply/', views.apply_job, name='apply'),
    path('', RedirectView.as_view(pattern_name='jobs-detail', permanent=True)),
    path("jobs/jobseeker/", UserUpload.as_view(), name='index2.html'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drf_and_image_uploads/apps/accounts/models.py
import os
import sys

from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager as UserManagerBase
from django.utils import timezone

if "makemigrations" in sys.argv:
    from django.utils.translation import gettext_noop as _
else:
    from django.utils.translation import gettext_lazy as _

"""JOB_TYPES = (
    ('Full Time', 'Full Time'),
    ('Contract', 'Contract Time'),
    ('Internship', 'Internship'),
    ('Industrial Attachment', 'Industrial Attachment'),
)

EXPERIENCE_LEVEL = [
    ('ENTRY-LEVEL', 'ENTRY-LEVEL'),
    ('INTERMEDIATE-LEVEL', 'INTERMEDIATE-LEVEL'),
    ('MID-LEVEL', 'MID-LEVEL'),
    ('SENIOR OR EXECUTIVE-LEVEL', 'SENIOR OR EXECUTIVE-LEVEL'),
]"""

COUNTIES_LIST = (
    ('1', 'Mombasa'), ('2', "Nairobi"), ('3', 'Kisumu'), ('4', 'Nakuru'), ('5', 'Namanga'),
    ('6', 'Kilifi'), ('7', 'Kwale'), ('8', 'Eldoret'), ('9', 'Moyale'), ('10', 'Busia'),
)


def upload_to(instance, filename):
    now = timezone.now()
    base, extension = os.path.splitext(filename.lower())
    milliseconds = now.microsecond // 1000
    return f"users/{instance.pk}/{now:%Y%m%d%H%M%S}{milliseconds}{extension}"


class UserManager(UserManagerBase):
    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        if not username:
            username = email
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if not username:
            username = email
        return self._create_user(username, email, password, **extra_fields)


class User(AbstractUser):
    # change username to non-editable non-required field
    username = models.CharField(
        _("username"), max_length=150, editable=False, blank=True
    )
    # change email to unique and required field
    email = models.EmailField(_("email address"), unique=True)
    cover = models.FileField(_("cover letter"), upload_to=upload_to, blank=True)
    resume = models.FileField(_("resume"), upload_to=upload_to, blank=True)
    id_number = models.CharField(max_length=50, default='777')
    middle_name = models.CharField(max_length=150, default='777')
    first_two_names = models.CharField(max_length=150)
    contact = models.CharField(max_length=20, default='777')
    location = models.CharField(max_length=50, default='Nairobi')

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["password"]

    def __str__(self):
        return self.first_two_names

drf_and_image_uploads/apps/accounts/views.py
from django.contrib.auth import get_user_model
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .serializers import UserUploadSerializer

User = get_user_model()


class UserDocUpload(APIView):
    parser_classes = [MultiPartParser, FormParser]
    permission_classes = [IsAuthenticated]

    @csrf_exempt
    def post(self, request, format=None):
        serializer = UserUploadSerializer(data=request.data, instance=request.user)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK, context_instance=RequestContext(request))
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @csrf_exempt
    def get(self, request, *args, **kwargs):
        query_set = User.objects.get(pk=request.user)
        serializer = UserUploadSerializer(query_set)
        if serializer.is_valid():
            return Response(serializer.data, status=status.HTTP_200_OK, context_instance=RequestContext(request))
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    """@csrf_exempt
    def put(self, request, pk, format=None):
        user = self.get_object(pk)
        serializer = UserUploadSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)"""

    """def delete(self, request, pk, format=None):
        user = self.get_object(pk)
        user.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)"""

drf_and_image_uploads/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    {% include 'jobseeker/navbar.html' %}

    {% block body %} {% endblock %}

    <!-- jQuery, Popper.js & Bootstrap JS -->
    <!-- Scripts applicable to current/one file -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <script>
        // Bootstrap 5: Activate popovers
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })
        // Bootstrap 5: Activate Tooltips
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        });
    </script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/menu.js' %}"></script>
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/e307a20384.js" crossorigin="anonymous"></script>
    <!-- Bootstrap ICONS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    {% block scripts %}{% endblock %}
    </body>

</html>

drf_and_image_uploads/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Job Application</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <p class="text-muted my-3"><small>KEBS Simple Application Process.</small></p>
            <h3 class="my-3">1. Log in</h3>
            <form id="login_form" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Email address</label>
                    <input type="email" class="form-control" id="id_email" aria-describedby="emailHelp"
                           placeholder="Enter email"/>
                </div>
                <div class="form-group">
                    <label for="id_password">Password: </label>
                    <input type="password" class="form-control" id="id_password" placeholder="Password"/>
                </div>
                <button type="submit" class="btn btn-primary">Log in</button>
            </form>

            <h3 class="my-3">2. Application Details</h3>

            <form id="avatar_form" method="post">
                {% csrf_token %}
                <div class="form-group">
                <label for="id_number">How Did you hear about this application? </label>
                <select class="form-control" id="id_number">
                    <option value="---">---</option>
                    <option value="KEBS CAREERS">KEBS Careers Page</option>
                    <option value="Recommended by a friend or colleague">Recommended by a friend or colleague</option>
                    <option value="Google/Search engine">Google/Search engine</option>
                    <option value="Newspaper Advertisement">Newspaper Advertisement or similar</option>
                    <option value="LinkedIn">LinkedIn</option>
                    <option value="Other">Other</option>
                </select></div>

                <h5 class="my-3">2.1 Personal Details</h5>
                <div class="form-group">
                    <label for="id_email2">Email address</label>
                    <input type="email" class="form-control" id="id_email2" aria-describedby="emailHelp"
                           placeholder="Enter email"/>
                </div>

                <div class="form-group">
                    <label for="id_first_two_names">First & Surname/Maiden Names: </label>
                    <input type="text" class="form-control" id="id_first_two_names" placeholder="First Surname/Maiden "/>
                </div><small></small>
                <div class="form-group">
                    <label for="id_middle_name">Middle Name <small>(IGNORE IF ONLY TWO NAMES)</small>: </label>
                    <input type="text" class="form-control" id="id_middle_name" placeholder="Middle Name"/>
                </div>
                <div class="form-group">
                    <label for="id_contact">Contact: </label>
                    <input type="text" class="form-control" id="id_contact" placeholder="254712345678"/>
                </div><small></small>

                <div class="form-group">
                    <label for="id_location">Location: </label>
                    <input type="text" class="form-control" id="id_location" placeholder="Nairobi"/>
                </div>
                <!--
                <div class="form-group">
                <label for="id_location">Location </label>
                <select class="form-control" id="id_location">
                    <option value="---">---</option>
                    <option value="Nairobi">Nairobi</option>
                    <option value="Nakuru">Nakuru</option>
                    <option value="Kisumu">Kisumu</option>
                    <option value="Mombasa">Mombasa</option>
                    <option value="Namanga">Namanga</option>
                    <option value="LinkedIn">LinkedIn</option>
                    <option value="Other">Other</option>
                </select></div>
                -->
                <h5 class="my-3">2.2 Add Personal Documents</h5>
                <div class="form-group">
                    <label for="id_bio">Cover Letter : </label>
                    <input type="file" class="form-control-file" id="id_bio"/>
                </div><small></small>
                <div class="form-group">
                    <label for="id_resume">Resume : </label>
                    <input type="file" class="form-control-file" id="id_resume"/>
                </div><small></small>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'site/js/avatar.js' %}"></script>
</body>
</html>

drf_and_image_uploads/templates/indexcp.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Avatar Upload</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <p class="text-muted my-3"><small>Open Developer Console for information about responses.</small></p>
            <h1 class="my-3">1. Log in</h1>
            <form id="login_form">
                <div class="form-group">
                    <label for="id_email">Email address</label>
                    <input type="email" class="form-control" id="id_email" aria-describedby="emailHelp"
                           placeholder="Enter email"/>
                </div>
                <div class="form-group">
                    <label for="id_password">Password: </label>
                    <input type="password" class="form-control" id="id_password" placeholder="Password"/>
                </div>
                <div class="form-group">
                    <label for="id_number">ID Number: </label>
                    <input type="text" class="form-control" id="id_number" placeholder="Enter email"/>
                </div>
                <div class="form-group">
                    <label for="id_first_two_names">First Two Names: </label>
                    <input type="text" class="form-control" id="id_first_two_names" placeholder="Enter email"/>
                </div>
                <div class="form-group">
                    <label for="id_contact">Contact: </label>
                    <input type="text" class="form-control" id="id_contact" placeholder="254712345678"/>
                </div>
                <div class="form-group">
                    <label for="id_location">Location: </label>
                    <input type="text" class="form-control" id="id_location" placeholder="Nairobi"/>
                </div>
                <button type="submit" class="btn btn-primary">Log in</button>
            </form>

            <h1 class="my-3">2. Application Details</h1>
            <form id="avatar_form">
                <div class="form-group">
                    <label for="id_avatar">Cover Letter: </label>
                    <input type="file" class="form-control-file" id="id_avatar"/>
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>



 <!--


                <div class="form-group">
                    <label for="id_number">ID Number: </label>
                    <input type="text" class="form-control" id="id_number" placeholder="ID Number"/>
                </div>
                <div class="form-group">
                    <label for="id_first_two_names">First Two Names: </label>
                    <input type="text" class="form-control" id="id_first_two_names" placeholder="Enter email"/>
                </div>
                <div class="form-group">
                    <label for="id_contact">Contact: </label>
                    <input type="text" class="form-control" id="id_contact" placeholder="254712345678"/>
                </div>
                <div class="form-group">
                    <label for="id_location">Location: </label>
                    <input type="text" class="form-control" id="id_location" placeholder="Nairobi"/>
                </div>
 -->

            </form>

            <form id="avatar_form2">
                <div class="form-group">
                    <label for="id_resume">CV/RESUME: </label>
                    <input type="file" class="form-control-file" id="id_resume"/>
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>

        </div>
    </div>
</div>
<script src="{% static 'site/js/avatar.js' %}"></script>
</body>
</html>